### DISCUSSION TITLE
clash 的 DNS 设置为其他口时，DNS 劫持失败

### DISCUSSION THREAD

**Discussion by ghost** [zzzgydi/clash-verge#426] [Q&A]
OS: Ubuntu 22.04 amd64
clash: 1.10.0 meta

通过 clash-verge 查询的配置:

dns 配置:

```yaml
dns:
  enable: true
  listen: 127.0.0.1:53353
  ipv6: true
  default-nameserver:
  - 223.5.5.5
  - 114.114.114.114
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  nameserver:
  - 114.114.114.114
  - 223.5.5.5
  - 8.8.8.8
```

tun 配置：

```yaml
tun:
  enable: true
  stack: gvisor
  dns-hijack:
  - 192.168.0.235:53
  - 127.0.0.1:53
  - any:53
  auto-route: true
  auto-detect-interface: true
  strict_route: false
```

使用命令 `dig www.google.com` 查询到的是被污染的 ip，但是 `dig www.google.com @127.0.0.1 -p 53353` 就能得到 fake-ip，请问有什么解决办法吗？

我只想远程解析配置，所以不想在本地配置 dns
