### ISSUE TITLE
安装完成后不管任何操作都会显示failed to parse the server 端口也无法进行设置

### ISSUE THREAD

**Issue by nowata** [zzzgydi/clash-verge#108]
只能进行导入操作 除此之外无法进行任何操作 甚至还会卡死

**Comment by zzzgydi** [comment]
可以看看 config.yaml 的 external-controller 的值

**Comment by nowata** [comment]
config.yaml 里只有以下内容

# Default Config For Clash Core

---
mixed-port: 1000

**Comment by nowata** [comment]
config.yaml 只有以下内容
# Default Config For Clash Core
---
mixed-port: 1000

**Comment by zzzgydi** [comment]
补充这些内容上去吧，是不是删过这个文件的内容。。

```yaml
log-level: info
allow-lan: false
mode: rule
external-controller: "127.0.0.1:9099"
```
