### ISSUE TITLE
failed to parse config.yaml file

### ISSUE THREAD

**Issue by duokebei** [zzzgydi/clash-verge#129]
我使用的是机场订阅链接，remote加载方式，当我右键点击使用这个订阅时，出现failed to parse config.yaml file这个错误

**Comment by duokebei** [comment]
> 在系统中退出程序，重新启动程序。

不行，还是没法用，我用的是win11

**Comment by zzzgydi** [comment]
可以看看你的`~/.config/clash-verge/config.yaml`文件的内容

**Comment by duokebei** [comment]
> 可以看看你`~/.config/clash-verge/config.yaml`文件的内容

# Default Config For Clash Core

---
mixed-port: 7990


这是整个config.yaml的内容，请问需要改些什么？

**Comment by zzzgydi** [comment]
```yaml
log-level: info
allow-lan: false
external-controller: 127.0.0.1:9090
mode: rule
```

这些加上，尤其是`external-controller`不能没有
