### ISSUE TITLE
在配置文件中写了 dns enable: true 但是好像还是用的系统dns？

### ISSUE THREAD

**Issue by GeorgeRudd** [zzzgydi/clash-verge#138]
```yaml
dns:
  enable: true
  nameserver:         
    - 119.29.29.29 
```
我是在这里测试的dns http://tool.mkblog.cn/dns/
同样的配置，使用clashN时 dns由119.29.29.29解析 https://github.com/2dust/clashN
但是clash-verge好像还是用的系统dns解析
请帮忙看一下原因 谢谢
