### ISSUE TITLE
对 YAML Merge Key 支持不好

### ISSUE THREAD

**Issue by Hubedge** [zzzgydi/clash-verge#165]
Docs https://yaml.org/type/merge.html

配置文件：
```yaml
url-test-default: &url-test-default
    type: url-test
    url: http://www.gstatic.com/generate_204
    interval: 300
    tolerance: 50
proxy-groups:
  - name: ♻️自动选择
    <<: *url-test-default
    use:
      - InHouse
      - BBB
```

生成的 Runtime config：
```yaml
proxy-groups:
  - name: ♻️自动选择
    "<<":
      type: url-test
      url: "http://www.gstatic.com/generate_204"
      interval: 300
      tolerance: 50
    use:
      - InHouse
      - BBB
```

预期的 Runtime config：
```yaml
proxy-groups:
  - name: ♻️自动选择
    type: url-test
    url: "http://www.gstatic.com/generate_204"
    interval: 300
    tolerance: 50
    use:
      - InHouse
      - BBB
```
或
```yaml
proxy-groups:
  - name: ♻️自动选择
    <<:
      type: url-test
      url: "http://www.gstatic.com/generate_204"
      interval: 300
      tolerance: 50
    use:
      - InHouse
      - BBB
```

其实这个部分算是clash.meta的bug，因为`"<<"`应当被视为`<<`，但clash.meta并没有这样做，并报`level=fatal msg="Parse config error: ProxyGroup ♻️自动选择: key 'type' missing"`

原版clash没测试过

**Comment by zzzgydi** [comment]
依赖的 `serde_yaml` 在0.9版本已经实现merge key了，我目前还是用的0.8版本的包。

0.9的改动有点多，最主要的是0.9生成的yaml的数组格式有点不友好。

```yaml
# 0.8
list:
  - type: 12
    name: 123
  - type: 123
    name: 312

#0.9
list:
- type: 12
  name: 123
- type: 123
  name: 312
```
