### ISSUE TITLE
引用 proxy-providers 内节点延迟无法显示

### ISSUE THREAD

**Issue by jiesou** [zzzgydi/clash-verge#167]
在 proxy-groups 中用 use 引用 proxy-providers 的节点，无法显示延迟。且用 proxies 引用的自定节点没有问题
![image](https://user-images.githubusercontent.com/84175239/185630008-60d9a556-4934-4055-b835-683ff2531dc2.png)

对比 Clash for Windows 换 Meta 内核是没问题的
![image](https://user-images.githubusercontent.com/84175239/185629735-08019d19-bf79-4418-b183-9cc3256dabaa.png)

**Comment by ileeoyo** [comment]
同一个问题[https://github.com/zzzgydi/clash-verge/issues/49](https://github.com/zzzgydi/clash-verge/issues/49)

**Comment by zzzgydi** [comment]
71e69003757201207cfbd35fdb0ddea0faf172a3 昨天加了provider的测速支持，下个版本发布，稍等

**Comment by zzzgydi** [comment]
v1.1.0已经支持，可以更新一下

**Comment by mo-han** [comment]
我不知道我遇到的问题是不是和这个issue完全一致，但是有相同点。
clash-verge版本是v1.1.1。

这边也是group引用provider，延迟测试的结果倒是有，但并不是我自己点击“延迟测试”的按钮后出的结果，更像是provider自己定时检测出来的结果，然后，似乎理所应当地，我想让它们按照测试结果排序也是没用，切换到“默认”和“按名称”排序，代理列表都会改变排序，但“按延迟排序”没变化。
![图片](https://user-images.githubusercontent.com/9916948/199880773-e08d3e31-20e6-4b74-8407-029fa6303f2d.png)
下面是代理节点相关的配置截取（都是免费分享的节点，随便贴了）
```yaml
proxy-providers:
  aiboboxx/clashfree:
    type: http
    url: https://raw.githubusercontent.com/aiboboxx/clashfree/main/clash.yml
    interval: 86400
    path: ./proxy-provider/aiboboxx/clashfree.yaml
    health-check:
      enable: true
      interval: 60
      lazy: true
      url: http://www.gstatic.com/generate_204

proxy-groups:
  - name: PROXY
    type: select
    proxies:
      - DIRECT
      - aiboboxx/clashfree
      # - aiboboxx/clashfree (auto)
  # - name: aiboboxx/clashfree (auto)
  #   type: url-test
  #   url: http://www.gstatic.com/generate_204
  #   interval: 300
  #   tolerance: 300
  #   use:
  #     - aiboboxx/clashfree
  - name: aiboboxx/clashfree
    type: select
    url: http://www.gstatic.com/generate_204
    use:
      - aiboboxx/clashfree
```

我是不是哪里还没设置对，或者说这就是按照设计所应该有的特征，还是说这是目前clash-verge的bug
