### ISSUE TITLE
请问如何做到在远程配置上添加自己的节点呢

### ISSUE THREAD

**Issue by jmdweem** [zzzgydi/clash-verge#174]
目前想要达成的效果是这样：
我有一个远程配置，然后自己建的也有节点，希望能做到远程配置定期更新的前提下，将自己的节点也加入，直接在代理里面切换节点即可，而不用切换配置。
谢谢啦

**Comment by zzzgydi** [comment]
可以新建一个merge profile用yaml增加一些节点，或者用script profile写js增加节点

**Comment by jmdweem** [comment]
> 可以新建一个merge profile用yaml增加一些节点，或者用script profile写js增加节点

请问可以给个范例吗，之前用
···
prepend-rules:

prepend-proxies:

prepend-proxy-groups:

append-rules:

append-proxies:
  - {name: example, server: xxx, port: xxx, type: ss, cipher: xxx, password: xxx, udp: true}

append-proxy-groups:
  - name: Proxy
    type: select
    proxies:
      - example
···
这样的merge file貌似没有效果
谢谢

**Comment by zzzgydi** [comment]
有没有开启配置，默认是禁用的，需要右键点开启才生效

**Comment by jmdweem** [comment]
已经右键选择->启用了
目前是这样的，远程配置文件如下:
```yaml
port: 7890
socks-port: 7891
allow-lan: true
mode: Rule
log-level: info
external-controller: :9090
proxies:
  - {name: AAA, server: xxx.xxx.xxx.xxx, port: 123, type: ss, cipher: XXX, password: X}
  - {name: BBB, server: xxx.xxx.xxx.xxx, port: 123, type: ss, cipher: XXX, password: X}
proxy-groups:
  - name: Proxy
    type: select
    proxies:
      - DIRECT
      - AAA
      - BBB
```

然后merge file如下:

```yaml
prepend-rules:

prepend-proxies:

prepend-proxy-groups:

append-rules:

append-proxies:
  - {name: CCC, server: xxx.xxx.xxx.xxx, port: XXX, type: ss, cipher: xxx, password: xxx}

append-proxy-groups:
  - name: Proxy
    type: select
    proxies:
      - CCC
```

希望达到的效果是:

```yaml
port: 7890
socks-port: 7891
allow-lan: true
mode: Rule
log-level: info
external-controller: :9090
proxies:
  - {name: AAA, server: xxx.xxx.xxx.xxx, port: 123, type: ss, cipher: XXX, password: X}
  - {name: BBB, server: xxx.xxx.xxx.xxx, port: 123, type: ss, cipher: XXX, password: X}
  - {name: CCC, server: xxx.xxx.xxx.xxx, port: XXX, type: ss, cipher: xxx, password: xxx}
proxy-groups:
  - name: Proxy
    type: select
    proxies:
      - DIRECT
      - AAA
      - BBB
      - CCC
```
十分感谢

**Comment by zzzgydi** [comment]
```yaml
append-proxy-groups:
  - name: Proxy
    type: select
    proxies:
      - example
```

这个会再新增一个同名的proxy group，不能达到你想要的效果。你这个要写个js脚本来完成才行。大致如下：

```js
function main(config) {
  config.proxies.push({
    name: "CCC",
    server: "",
    port: 123,
    type: "ss",
  });

  const group = config["proxy-groups"].find((item) => item.name === "Proxy");
  if (group) {
    group.proxies.push("CCC");
  }

  return config;
}
```
