### ISSUE TITLE
不能像cfw那样使用Proxy-Providers

### ISSUE THREAD

**Issue by justdoiting** [zzzgydi/clash-verge#176]
用别人的懒人配置，修改里面订阅链接之后丢到cfw里面会自动下载订阅和规则，而导入到clash-verge只会在配置目录生成一个一模一样的文件

配置文件模板是yaml格式的，因为格式不支持所以改成txt上传上来了
[懒人配置4.0.txt](https://github.com/zzzgydi/clash-verge/files/9439220/4.0.txt)

**Comment by zzzgydi** [comment]
proxy-providers里的path是`./Proxies/xxx.yaml`，所以会在配置目录生成这个文件

**Comment by justdoiting** [comment]
> proxy-providers里的path是`./Proxies/xxx.yaml`，所以会在配置目录生成这个文件

不管是proxy还是rules，配置文件设置的目录都没有创建，文件也没有下载下来，只在 .config/clash-verge/profile 生成一个内容和懒人配置相同的不同名文件
报错日志是  - failed to activate clash with status "400 Bad Request"  用的是clash-meta核1.12    verge版本是1.0.5

软件运行界面
![image](https://user-images.githubusercontent.com/109136320/187184559-41a17933-dfcf-44d7-97e7-f1423924dc63.png)

**Comment by zzzgydi** [comment]
400 的话，是配置本身有问题。应该是proxy-providers里用到了yaml的merge key https://github.com/zzzgydi/clash-verge/issues/165 ，现在对这个的处理没做好。

**Comment by justdoiting** [comment]
> 400 的话，是配置本身有问题。应该是proxy-providers里用到了yaml的merge key #165 ，现在对这个的处理没做好。

看了#165，确实有这个问题，存在<<: 这个键值

**Comment by zzzgydi** [comment]
v1.1.0已经修复这个问题，可以更新一下

**Comment by lakako** [comment]
我也碰到了这个问题，系统是archlinux，clash-verge的版本是1.1.1。clash-meta使用这个配置文件是没有问题的

```
mixed-port: 7890
allow-lan: true
mode: Rule
log-level: info
external-controller: "127.0.0.1:9090"
bind-address: "*"

proxy-providers:
  zzzList:
    type: http
    path: ./proxies/xxx.yml
    url: https://xxxxxxxxxx
    interval: 3600
    health-check:
      enable: false
      url: http://www.gstatic.com/generate_204
      interval: 300

proxies:
  - name: "54proxy"
    type: ss
    server: 111.222.333.444
    port: 8388
    cipher: aes-256-gcm
    password: xxxxx

proxy-groups:
  - name: "PROXY"
    type: select
    use:
      - zzzList

  - name: "54PROXY"
    type: select
    proxies:
      - 54proxy
      # - DIRECT

dns:
  enable: false
  default-nameserver:
    - 119.29.29.29
  enhanced-mode: redir-host # or fake-ip
  nameserver:
    - 119.29.29.29
    - https://dns.alidns.com/dns-query
  fallback:
    - https://1.1.1.1/dns-query
    - 8.8.8.8

    #- "https://dns.google/dns-query"
    # - 'tls://1.1.1.1:853'
    # - 'tls://8.8.8.8:853'
  fake-ip-filter:
    - "*.lan"
    - "ping.archlinux.org"
  fallback-filter:
    geoip: true
    ipcidr:
      - 240.0.0.0/4

tun:
  enable: false
  stack: system
  dns-hijack:
    - 198.18.0.2:53
#  auto-route: true
#  auto-detect-interface: true



rule-providers:
  reject:
    type: http
    behavior: domain
    url: "https://ghproxy.com/https://raw.githubusercontent.com/Loyalsoldier/clash-rules@release/reject.txt"
    path: ./ruleset/reject.yaml
    interval: 86400

  icloud:
    type: http
    behavior: domain
    url: "https://ghproxy.com/https://raw.githubusercontent.com/Loyalsoldier/clash-rules@release/icloud.txt"
    path: ./ruleset/icloud.yaml
    interval: 86400

  apple:
    type: http
    behavior: domain
    url: "https://ghproxy.com/https://raw.githubusercontent.com/Loyalsoldier/clash-rules@release/apple.txt"
    path: ./ruleset/apple.yaml
    interval: 86400

  google:
    type: http
    behavior: domain
    url: "https://ghproxy.com/https://raw.githubusercontent.com/Loyalsoldier/clash-rules@release/google.txt"
    path: ./ruleset/google.yaml
    interval: 86400

  proxy:
    type: http
    behavior: domain
    url: "https://ghproxy.com/https://raw.githubusercontent.com/Loyalsoldier/clash-rules@release/proxy.txt"
    path: ./ruleset/proxy.yaml
    interval: 86400

  direct:
    type: http
    behavior: domain
    url: "https://ghproxy.com/https://raw.githubusercontent.com/Loyalsoldier/clash-rules@release/direct.txt"
    path: ./ruleset/direct.yaml
    interval: 86400

  private:
    type: http
    behavior: domain
    url: "https://ghproxy.com/https://raw.githubusercontent.com/Loyalsoldier/clash-rules@release/private.txt"
    path: ./ruleset/private.yaml
    interval: 86400

  gfw:
    type: http
    behavior: domain
    url: "https://ghproxy.com/https://raw.githubusercontent.com/Loyalsoldier/clash-rules@release/gfw.txt"
    path: ./ruleset/gfw.yaml
    interval: 86400

  greatfire:
    type: http
    behavior: domain
    url: "https://ghproxy.com/https://raw.githubusercontent.com/Loyalsoldier/clash-rules@release/greatfire.txt"
    path: ./ruleset/greatfire.yaml
    interval: 86400

  tld-not-cn:
    type: http
    behavior: domain
    url: "https://ghproxy.com/https://raw.githubusercontent.com/Loyalsoldier/clash-rules@release/tld-not-cn.txt"
    path: ./ruleset/tld-not-cn.yaml
    interval: 86400

  telegramcidr:
    type: http
    behavior: ipcidr
    url: "https://ghproxy.com/https://raw.githubusercontent.com/Loyalsoldier/clash-rules@release/telegramcidr.txt"
    path: ./ruleset/telegramcidr.yaml
    interval: 86400

  cncidr:
    type: http
    behavior: ipcidr
    url: "https://ghproxy.com/https://raw.githubusercontent.com/Loyalsoldier/clash-rules@release/cncidr.txt"
    path: ./ruleset/cncidr.yaml
    interval: 86400

  lancidr:
    type: http
    behavior: ipcidr
    url: "https://ghproxy.com/https://raw.githubusercontent.com/Loyalsoldier/clash-rules@release/lancidr.txt"
    path: ./ruleset/lancidr.yaml
    interval: 86400

  applications:
    type: http
    behavior: classical
    url: "https://ghproxy.com/https://raw.githubusercontent.com/Loyalsoldier/clash-rules@release/applications.txt"
    path: ./ruleset/applications.yaml
    interval: 86400
  
  bilibili:
    type: http
    behavior: classical
    url: "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/BiliBili/BiliBili.yaml"
    path: "./ruleset/bilibili.yaml"
    interval: 86400

rules:
  - RULE-SET,applications,DIRECT
  - DOMAIN,clash.razord.top,DIRECT
  - DOMAIN,yacd.haishan.me,DIRECT
  - RULE-SET,private,DIRECT
  - RULE-SET,reject,REJECT
  - RULE-SET,icloud,DIRECT
  - RULE-SET,apple,DIRECT
  - RULE-SET,google,DIRECT
  - RULE-SET,proxy,PROXY
  - RULE-SET,direct,54PROXY
  - RULE-SET,lancidr,DIRECT
  - RULE-SET,cncidr,DIRECT
  - RULE-SET,telegramcidr,PROXY
  - GEOIP,,DIRECT
  - GEOIP,CN,DIRECT
  - MATCH,PROXY
```
