### ISSUE TITLE
某些机场的配置文件不能生效

### ISSUE THREAD

**Issue by inRm3D** [zzzgydi/clash-verge#183]
目前情况：

1. CFAndroid 能用，排除机场自身问题
2. 本项目不能用
3. 本项目能用别的机场，软件本身没问题

目前猜测是配置文件没有被支持。配置文件部分如下（已删除敏感信息）。

```yaml
mixed-port: 7890
allow-lan: true
bind-address: '*'
mode: rule
log-level: info
external-controller: '127.0.0.1:9090'
dns:
    enable: true
    listen: '0.0.0.0:5553'
    ipv6: false
    default-nameserver: [119.29.29.29, 223.5.5.5]
    enhanced-mode: fake-ip
    fake-ip-range: 198.18.0.1/16
    use-hosts: true
    fake-ip-filter: [+.lan, +.cn, +.10010.com, +.chinaunicom.com, +.baidu.com, '*.alipay.com', '*.alipayobjects.com', '*.jijifun.com', connect.rom.miui.com, localhost.ptlogin2.qq.com, dl.google.com, '+.stun.*.*', '+.stun.*.*.*', '+.stun.*.*.*.*', '+.stun.*.*.*.*.*', lens.l.google.com, '*.n.n.srv.nintendo.net', +.stun.playstation.net, '*.msftncsi.com', '*.msftconnecttest.com', '*.mcdn.bilivideo.cn', ntp.ntsc.ac.cn]
    nameserver: ['https://rubyfish.cn/dns-query', 'https://dns.alidns.com/dns-query', 'https://doh.pub/dns-query']
    fallback: ['https://8.8.4.4/dns-query', 'https://1.0.0.1/dns-query', 'https://dns.adguard.com/dns-query', 'https://doh.dns.sb/dns-query']
    fallback-filter: { geoip: true, ipcidr: [240.0.0.0/4, 0.0.0.0/32] }
proxies:
    - { name: xx, type: vmess, server: xxx, port: '16617', uuid: xxxxx, alterId: 0, cipher: auto, udp: true, network: ws }
```

正常使用的配置文件

![image](https://user-images.githubusercontent.com/64240055/188499354-707e5014-974f-42bf-83ab-98d951112a99.png)

这个机场的配置文件

![image](https://user-images.githubusercontent.com/64240055/188499511-a9af3421-dc08-4f0d-aef5-e6757dd0e861.png)

---

因为这个是 vmess 节点，初步怀疑是

https://github.com/Fndroid/clash_for_windows_pkg/issues/2588

的问题。

顺便问下 link 里的 parser 在本项目里对应哪个功能。
