### ISSUE TITLE
tun模式无法命中域名，全命中IP

### ISSUE THREAD

**Issue by ileeoyo** [zzzgydi/clash-verge#19]
手动增加了wintun.ddl，并且管理员启动，tun模式正常能用。但是tun模式下，域名规则无法命中，全命中了IP规则或者命中最后的“漏网之鱼”。已知开启了fake-ip和dns-hijack。用其他GUI或者clash core直接启动，是能够正常域名命中的。部分配置如下

```yaml
# 混合代理端口
mixed-port: 1080

# 允许局域网的连接
allow-lan: true

# 绑定局域网ip
bind-address: "*"

# Clash 的 RESTful API
external-controller: "127.0.0.1:9090"

# RESTful API 的口令
secret: ""

# 规则模式：Rule（规则） / Global（全局代理）/ Direct（全局直连）
mode: Rule

# 设置日志输出级别 (默认级别：silent，即不输出任何内容，以避免因日志内容过大而导致程序内存溢出）。
# 5 个级别：silent / info / warning / error / debug。级别越高日志输出量越大，越倾向于调试，若需要请自行开启。
log-level: info

ipv6: true

# 您可以将静态网页资源（如 clash-dashboard）放置在一个目录中，clash 将会服务于 `${API}/ui`
# external-ui: folder

dns:
    enable: true
    # or redir-host
    enhanced-mode: fake-ip
    # fake ip 池
    fake-ip-range: 198.18.0.1/16
    use-hosts: true # lookup hosts and return IP record
    # fake ip 白名单
    fake-ip-filter:
        - "*.lan"
        - localhost
        - "gitee.com"
        - "github.com"
    # 用于解析nameserver中的域名
    default-nameserver:
        - 114.114.114.114
        - 8.8.8.8
    nameserver:
        - 119.29.29.29
        - 223.5.5.5
    # 与 nameserver 内的服务器列表同时发起请求，当规则符合 GEOIP 在 CN 以外时，fallback 列表内的域名服务器生效。F
    fallback:
        - tls://dot.pub:853
        - https://doh.pub/dns-query
    fallback-filter:
        geoip: true # 默认
        ipcidr: # 在这个网段内的 IP 地址会被考虑为被污染的 IP
            - 240.0.0.0/4
tun:
    enable: true
    stack: system # gvisor
    dns-hijack:
        - 198.18.0.2:53
    auto-route: true
    auto-detect-interface: true
...

# 规则
rules:
    # 网易云音乐APP
    - PROCESS-NAME,cloudmusic.exe,🎵网易云
    # 代理服务器
    - DOMAIN-SUFFIX,ilee.gq,DIRECT
    - DOMAIN-SUFFIX,ilee.ga,DIRECT
    - PROCESS-NAME,Clash.exe,DIRECT
    - PROCESS-NAME,xray.exe,DIRECT
    - PROCESS-NAME,wv2ray.exe,DIRECT
    - PROCESS-NAME,v2ray.exe,DIRECT

    - RULE-SET,Unbreak,🍪国内服务
    - RULE-SET,CustomDirect,DIRECT
    - RULE-SET,CustomGlobal,🔰国际服务
    - RULE-SET,Speedtest,💤测速
    - RULE-SET,China,🍪国内服务
    - RULE-SET,Streaming,🎥国际媒体
    - RULE-SET,StreamingSE,🎥国际媒体
    - RULE-SET,Global,🔰国际服务
    - RULE-SET,Global2,🔰国际服务

    ############## IP规则 ##################

    # 家庭局域网
    - IP-CIDR,192.168.2.0/24,🏠回家
    # Local Area Network
    - RULE-SET,LocalAreaIP,DIRECT
    # 使用来自 ipipdotnet 的 ChinaIP 以解决数据不准确的问题，使用 ChinaIP.yaml 时可禁用下列直至（包括）「GEOIP,CN」规则
    - RULE-SET,ChinaIP,🍪国内服务
    # GeoIP China
    # - GEOIP,CN,DIRECT
    - MATCH,🐟默认
```
见log
[2022-03-10-103751.log](https://github.com/zzzgydi/clash-verge/files/8219982/2022-03-10-103751.log)

**Comment by zzzgydi** [comment]
issue先待定处理，因为我也不清楚。

**Comment by Roiyaru** [comment]
这个有没有可能是解析速度慢的原因？

**Comment by ileeoyo** [comment]
> 这个有没有可能是解析速度慢的原因？
解析不慢，比如访问www.baidu.com，马上log里就看到了百度的IP访问记录，但是命中了ChinaIp规则，没有命中China规则。China规则在ChinaIp规则上面，且有百度的域名记录，理论上是先命中域名的

**Comment by Roiyaru** [comment]
几次测试下来我的也是不行，匹配到的全是全球直连和漏网之鱼。
[Uploading 2022-03-10-125636.log…]()

**Comment by ileeoyo** [comment]
> 几次测试下来我的也是不行，匹配到的全是全球直连和漏网之鱼。 Uploading 2022-03-10-125636.log…

@Roiyaru 看来也是bug，参见作者的回答。[https://github.com/zzzgydi/clash-verge/issues/16#issuecomment-1063616212](https://github.com/zzzgydi/clash-verge/issues/16#issuecomment-1063616212)
另外你每次上传log文件时，还未传成功就提交了，导致你传的文件无法查看。

**Comment by Roiyaru** [comment]
> > 几次测试下来我的也是不行，匹配到的全是全球直连和漏网之鱼。 Uploading 2022-03-10-125636.log…
> 
> @Roiyaru 看来也是bug，参见作者的回答。[#16 (comment)](https://github.com/zzzgydi/clash-verge/issues/16#issuecomment-1063616212) 另外你每次上传log文件时，还未传成功就提交了，导致你传的文件无法查看。

😂，我看到浏览器的百分比进度走完才点的提交，看来以后要再等一会再提交。

**Comment by zzzgydi** [comment]
tun模式 + socks的代理好像有点问题，测了一下cfw也有问题，有遇到的吗

**Comment by ileeoyo** [comment]
> tun模式 + socks的代理好像有点问题，测了一下cfw也有问题，有遇到的吗

我用cdn是正常，cfw没有过。单独跑core也是OK的

**Comment by zzzgydi** [comment]
> 我用cdn是正常，cfw没有过。单独跑core也是OK的

core也测了一下，感觉可能是tun没写对，再研究研究。Thanks!

**Comment by ttys3** [comment]
@zzzgydi  clash domain matching is based on DNS query.

In order to match a domain, the client machine must set DNS to clash.

**Comment by Roiyaru** [comment]
0.23版本tun模式依旧不走分流规则，我在系统设置了DOH，不知道这个有没有影响。
[2022-03-14-200021.log](https://github.com/zzzgydi/clash-verge/files/8244639/2022-03-14-200021.log)

**Comment by returnL** [comment]
> > 我用cdn是正常，cfw没有过。单独跑core也是OK的
> 
> core也测了一下，感觉可能是tun没写对，再研究研究。Thanks!

TUN没有写 `dns-hijack` 
比如在Windows系统下
```yaml
tun:
  enable: true
  stack: gvisor # 使用 system 需要 Clash Premium 2021.05.08 及更高版本
  dns-hijack:
    - 198.18.0.2:53
  auto-route: true
  auto-detect-interface: true # 自动检测出口网卡
```
