### ISSUE TITLE
无法下载subconverter转换后的订阅文件

### ISSUE THREAD

**Issue by EsuRt** [zzzgydi/clash-verge#247]
proxy-providers使用机场提供的订阅链接，在目录下可以看到下载后的yaml文件，但订阅链接用subconverter转换后，显示配置文件加载成功了，文件实际并没有下载。

**Comment by zzzgydi** [comment]
应该是转换后的地址访问不了了吧，可以用代理更新

**Comment by EsuRt** [comment]
> 应该是转换后的地址访问不了了吧，可以用代理更新
应该不是地址无法访问，使用代理后，依旧无法更新。把文件上传到gist后，也无法下载，gist可以不使用代理访问。

**Comment by zzzgydi** [comment]
可以试试v1.1.2版，应该修了这个问题

**Comment by EsuRt** [comment]
> 可以试试v1.1.2版，应该修了这个问题

测试了下，还是无法下载。目前系统用的是v2ray代理，但右键配置文件点击使用后，流量中却没有出现访问github的任何记录。

**Comment by zzzgydi** [comment]
你有没有右键使用代理更新，或者可以编辑信息-点击弹窗左下角的设置-选择clash proxy，看看clash有没有流量

**Comment by EsuRt** [comment]
> 你有没有右键使用代理更新，或者可以编辑信息-点击弹窗左下角的设置-选择clash proxy，看看clash有没有流量

使用的是本地文件，没有这些选项
![1](https://user-images.githubusercontent.com/15177069/199645061-a05d6be2-e6a0-451d-bb93-4a9e89f28d0f.jpg)

**Comment by zzzgydi** [comment]
你标题不是说无法下载subconverter转换的订阅吗，得用remote profile 填链接吧。如果是直接用本地文件，得看看你这个本地配置的内容格式是不是符合clash字段的，是不是yaml格式的

**Comment by EsuRt** [comment]
因为机场提供的订阅链接不支持clash meta格式，所以我自己写了个配置文件，然后用proxy-providers来提取机场的代理，但机场的代理是不启用udp的，所以要用subconverter修改udp设置。yaml格式是没有问题的，用机场的订阅链接能正常下载配置文件，但换成转换过的就不行（转换过的也没问题，openclash也能正常识别）。下面是本地配置文件和subconverter转换过的文件。

本地配置文件：
```
  port: 7890
  socks-port: 7891
  allow-lan: true
  mode: rule
  log-level: info
  external-controller: 0.0.0.0:9090
  proxies:
  - name: xxxxx
    password:
    server: xxxxxxx
    type: vmess
    port: 443
    cipher: auto
    uuid: xxxxxxxxxxxxxxx
    alterId: 0
    udp: true
  proxy-groups:
  - name: "🚀 节点选择"
    type: select
    disable-udp: false
    proxies:
    - xxxxx
    use:
    - aaaa
  - name: "🎯 全球直连"
    type: select
    disable-udp: false
    proxies:
    - DIRECT
  - name: "🐟 漏网之鱼"
    type: select
    disable-udp: false
    proxies:
    - "🚀 节点选择"
  proxy-providers:
    aaaa:
      type: http
      url: "https://gist.githubusercontent.com/xxxxxxx/raw/aaaa.yaml"
      interval: 3600
      path: ./aaaa.yaml
  rules:
  - DST-PORT,7895,REJECT
  - DST-PORT,7892,REJECT
  - IP-CIDR,198.18.0.1/16,REJECT,no-resolve
  - GEOSITE,geolocation-cn,DIRECT
  - "GEOSITE,geolocation-!cn,🚀 节点选择"
  - GEOIP,private,DIRECT,no-resolve
  - GEOIP,cn,DIRECT
  - "MATCH,🐟 漏网之鱼"
  redir-port: 7892
  tproxy-port: 7895
  mixed-port: 7893
  secret: '123456'
  bind-address: "*"
  ipv6: false
  geodata-mode: true
  geodata-loader: standard
  tcp-concurrent: false
  dns:
    enable: true
    ipv6: false
    enhanced-mode: redir-host
    listen: 0.0.0.0:7874
    nameserver:
    - https://223.5.5.5/dns-query
    proxy-server-nameserver:
    - https://1.1.1.1/dns-query
    fallback:
    - https://1.1.1.1/dns-query
    fallback-filter:
      geosite:
      - geolocation-!cn
      geoip: true
      geoip-code: CN
      ipcidr:
      - 0.0.0.0/8
      - 10.0.0.0/8
      - 100.64.0.0/10
      - 127.0.0.0/8
      - 169.254.0.0/16
      - 172.16.0.0/12
      - 192.0.0.0/24
      - 192.0.2.0/24
      - 192.88.99.0/24
      - 192.168.0.0/16
      - 198.18.0.0/15
      - 198.51.100.0/24
      - 203.0.113.0/24
      - 224.0.0.0/4
      - 240.0.0.0/4
      - 255.255.255.255/32
      domain:
      - "+.google.com"
      - "+.facebook.com"
      - "+.youtube.com"
      - "+.githubusercontent.com"
      - "+.googlevideo.com"
      - "+.msftconnecttest.com"
      - "+.msftncsi.com"
      - msftconnecttest.com
      - msftncsi.com
  sniffer:
    enable: true
    sniffing:
    - tls
    - http
  profile:
    store-selected: true
    store-fake-ip: true
```

subconverter转换过的配置文件：
```
port: 7890
socks-port: 7891
allow-lan: true
mode: Rule
log-level: info
external-controller: :9090
Proxy:
  - {name: 🇺🇸 美国 A01V, server: xxxxxx, port: xxx, type: vmess, uuid: xxxxxxxx, alterId: 0, cipher: auto, tls: false, skip-cert-verify: false, udp: true}
  - 其他省略
Proxy Group:
  - name: Proxies
    type: select
    proxies:
      - 🇺🇸 美国 A01V
      - 其他省略

Rule:
 - GEOIP,CN,DIRECT
 - MATCH,Proxies
```
