### ISSUE TITLE
本地导入多个配置文件更新后未生效问题

### ISSUE THREAD

**Issue by lvii** [zzzgydi/clash-verge#269]
Hi

版本 1.1.2 系统 macOS 12.6

平时使用 2 种配置文件场景：一个白名单、一个黑名单

之前使用传统的 ClashX 是直接支持多个配置文件模式，直接在菜单选择即可，文件更新后会重新加载立即生效。

verge 的配置文件管理比较特别。

没找到多个配置文件使用场景，只找到通过 【配置】页面新建选择 **local 本地导入** 的方式。

修改配置文件的代理列表，删掉一组代理后:
``` yaml
- name: PROXY
  type: select
  proxies:
  - mi-v2
  - mi-v1
  # - bd-v2
  # - bd-v1
  - AUTO
```

在【配置】页面右键配置文件选择【使用】菜单重载，还是加载的之前的配置文件。

尝试重启加载也还是不行：
- 重启 应用
- 重启 clash-meta

之前删掉了代理，还出现在代理页面：

![img](https://i.imgur.com/I61fGjR.png)
