### ISSUE TITLE
部分域名无法解析

### ISSUE THREAD

**Issue by EsuRt** [zzzgydi/clash-verge#390]
在玩游戏时发现部分域名无法解析，昨天是正常的，今天修改了下配置文件后，发现无法登录游戏，然后将配置文件恢复成昨天的内容后，依然无法登录，不知道问题出现在哪？其他网站能正常登陆，使用的是meta内核。
报错信息：
```
01-29 17:21:08WARNING
[TCP] dial DIRECT (match GeoSite/geolocation-cn) 127.0.0.1:2534 --> overseauspider.yuanshen.com:8888 error: all DNS requests failed, first error: requesting https://1.1.1.1:443/dns-query?dns=AAABAAABAAAAAAAADm92ZXJzZWF1c3BpZGVyCHl1YW5zaGVuA2NvbQAAAQAB: Get "https://1.1.1.1:443/dns-query?dns=AAABAAABAAAAAAAADm92ZXJzZWF1c3BpZGVyCHl1YW5zaGVuA2NvbQAAAQAB": interface not found (resErr:<nil>)
01-29 17:21:09WARNING
[TCP] dial DIRECT (match GeoSite/geolocation-cn) 198.18.0.1:2535 --> dispatchosglobal.yuanshen.com:443 error: all DNS requests failed, first error: requesting https://1.1.1.1:443/dns-query?dns=AAABAAABAAAAAAAAEGRpc3BhdGNob3NnbG9iYWwIeXVhbnNoZW4DY29tAAABAAE: Get "https://1.1.1.1:443/dns-query?dns=AAABAAABAAAAAAAAEGRpc3BhdGNob3NnbG9iYWwIeXVhbnNoZW4DY29tAAABAAE": interface not found (resErr:<nil>)
```

配置文件：
```
port: 7890
socks-port: 7891
ipv6: false
geodata-mode: true
tcp-concurrent: false
allow-lan: true
bind-address: "*"
mode: rule
log-level: debug
profile:
  store-selected: true
  store-fake-ip: true
sniffer:
  enable: true
  sniffing:
  - tls
  - http
dns:
  enable: true
  ipv6: false
  enhanced-mode: redir-host
  listen: 0.0.0.0:53
  default-nameserver:
  - 223.5.5.5  
  proxy-server-nameserver:
  - https://223.5.5.5/dns-query
  nameserver:
  - https://223.5.5.5/dns-query
  fallback:
  - 'https://1.1.1.1/dns-query#PROXY'
  fallback-filter:
    geosite:
    - geolocation-!cn
    geoip: true
    geoip-code: CN
proxies:
- xxxxx
proxy-groups:
- name: PROXY
  type: select
  disable-udp: false
  proxies:
  - xxxxxx
  - xxxxxx
  use:
  - aaa
proxy-providers:
  aaa:
    xxxxxxx
rules:
- GEOIP,private,DIRECT,no-resolve
- GEOSITE,geolocation-!cn,PROXY
- GEOSITE,geolocation-cn,DIRECT
- GEOIP,cn,DIRECT
- MATCH,PROXY
```
clash-verge设置：
启用TUN模式、服务模式和系统代理
