### ISSUE TITLE
clash meta内核不会自动测试延迟

### ISSUE THREAD

**Issue by ckaak** [zzzgydi/clash-verge#444]
嗨！开发者
我在windows上使用clash-verge v1.2.3 ，选择clash meta内核，节点不会自动测试所有节点延迟，换回clash内核就没问题。在clash meta安卓客户端也没问题。尝试过更换clash meta 最新测试版内核问题依旧。

下方是规则集，尝试过用订阅转换也不行。
```
    name: 自动选择
    type: url-test
    proxies:
      - 节点
    url: 'http://www.gstatic.com/generate_204'
    interval: 300
```
