### ISSUE TITLE
昨晚更新后，节点延迟测试`error`，但节点同样可用。版本：v1.2.3 -> v1.3.0 (Clash Premium 2023.01.29 -> 2023.03.04)

### ISSUE THREAD

**Issue by wolonge95** [zzzgydi/clash-verge#454]
以下是一个最小的配置：

```yaml
mixed-port: 7890
mode: rule
external-controller: 127.0.0.1:9090
log-level: debug
proxies:
  - name: 'xxx name'
    type: ss
    server: server
    port: *
    cipher: *
    password: *
proxy-groups:
  - name: High
    type: select
    proxies:
      - 'xxx name'
rules:
  # 最终规则
  - GEOIP,LAN,DIRECT
  - GEOIP,CN,DIRECT
  - MATCH,High
```

我更新一个不常用的客户端，同样测试不通过，节点可用。

然后我新找了一个使用 Clash.Meta 的客户端，他的节点测试都在 3000ms 往上。我将 clash-verge 换成 Clash.Meta 的内核仍然是`error`，（可能对超时时间有限制？）。

我折腾了好久，不确定是哪里的问题。我的配置、客户端、Clash 搞到现在有点头晕了。这是我在 Clash 的一个https://github.com/Dreamacro/clash/issues/2622  Issue。

需要帮助呀，谢谢大伙了。
