### ISSUE TITLE
关于订阅更新间隔的问题

### ISSUE THREAD

**Issue by luzibuye** [zzzgydi/clash-verge#487]
使用的订阅是v2ray格式的订阅，内核是clash meta，这样可以直接解析。但是，订阅更新的时机不是很理解。配置文件中相关配置如下：
```
proxy-providers:
  provider:
    type: http
    #【Meta专属】URL支持解析V2rayN等工具使用的普通订阅
    url: sub_url
    interval: 86400
    exclude-type: "ss" #不支持正则表达式，通过 "|" 分割，根据节点类型排除
    path: ./profiles/provider.yaml
    health-check:
      enable: true
      interval: 86400
      # lazy: true
      url: http://www.gstatic.com/generate_204
  provider_hk:
    type: http
    #【Meta专属】URL支持解析V2rayN等工具使用的普通订阅
    url: sub_url
    interval: 86400
    filter: 'hk'
    path: ./profiles/provider.yaml
    health-check:
      enable: true
      interval: 86400
      # lazy: true
      url: http://www.gstatic.com/generate_204
  provider_us:
    type: http
    #【Meta专属】URL支持解析V2rayN等工具使用的普通订阅
    url: sub_url
    interval: 86400
    filter: 'us'
    path: ./profiles/provider.yaml
    health-check:
      enable: true
      interval: 86400
      # lazy: true
      url: http://www.gstatic.com/generate_204
```
设置的更新间隔是86400，也就是24小时。
下面是一些log
```
03-29 10:29:53INFO
[TCP] clash.meta --> sub_url match Domain(sub_url) using DIRECT
03-29 10:30:01INFO
[TCP] clash.meta --> sub_url match Domain(sub_url) using DIRECT
03-29 10:30:01INFO
[TCP] clash.meta --> sub_url match Domain(sub_url) using DIRECT
03-29 10:30:01INFO
[TCP] clash.meta --> sub_url match Domain(sub_url) using DIRECT
03-29 10:30:03INFO
[TCP] clash.meta --> sub_url match Domain(sub_url) using DIRECT
03-29 10:30:03INFO
[TCP] clash.meta --> sub_url match Domain(sub_url) using DIRECT
03-29 10:30:03INFO
[TCP] clash.meta --> sub_url match Domain(sub_url) using DIRECT
03-29 10:30:04INFO
[TCP] clash.meta --> sub_url match Domain(sub_url) using DIRECT
03-29 10:30:04INFO
[TCP] clash.meta --> sub_url match Domain(sub_url) using DIRECT
03-29 10:30:05INFO
[TCP] clash.meta --> sub_url match Domain(sub_url) using DIRECT
```
可以看到，对订阅地址进行了频繁访问。因为使用的订阅网站对于每日订阅次数有限制，所以经常会出发限制，然后不能使用。
所以想请问一下，如何避免这种频繁更新订阅的情况。
