### ISSUE TITLE
有没有办法emoji显示国旗

### ISSUE THREAD

**Issue by spphinslove** [zzzgydi/clash-verge#50]
win11上emoji显示的是字母，linux版本就显示国旗

**Comment by zzzgydi** [comment]
换可以显示国旗emoji字体就可以了，新版加上可以增加自定义字体的设置

**Comment by spphinslove** [comment]
我还以为是chromium的问题，因为chromium都是显示字母，而firefox能显示国旗

**Comment by zzzgydi** [comment]
> 而firefox能显示国旗

好像是firefox自己带了字体

**Comment by zzzgydi** [comment]
昨晚实现了更换字体和注入css的功能（还有换主题色）。通过**设置字体**和**注入css片段**，比如`@font-face`的声明，就可以实现在windows里显示emoji国旗。

本地安装字体之后，填css片段，再在font-family里填上Flags即可。上面的`unicode-range`最好设置一下，不然可能有点小问题，这还是和引用的字体有关。下面贴一下css片段，参考链接：https://www.bilibili.com/read/cv13600525

```css
@font-face {
  font-family: Flags;
  src: local("Twemoji Mozilla");
  unicode-range: U+1F1E6-1F1FF, U+1F3F3-1F3F4, U+E0001-E007F;
}
```

src里可以用`local()`也可以用`url()`，不过可能要注意CSP限制的问题，我测试了`file://`协议不行，`https://`还是可以的。

**Comment by spphinslove** [comment]
> 

我把这段代码 填入主题设置-〉family font里面国旗还是没显示emoji

**Comment by zzzgydi** [comment]
https://github.com/mozilla/twemoji-colr/releases 可以在这里下载和安装字体，一定要本地安装，不然src就要填url

然后在 主题设置 -> CSS Injection里填入

```css
@font-face {
  font-family: Flags;
  src: local("Twemoji Mozilla");
  unicode-range: U+1F1E6-1F1FF, U+1F3F3-1F3F4, U+E0001-E007F;
}
```

然后在 主题设置 -> Font Family 里填入 `Flags`
