### ISSUE TITLE
指定geo更新问题

### ISSUE THREAD

**Issue by lhbdhr** [zzzgydi/clash-verge#526]
有个问题想请教一下，

```yaml
geodata-mode: true
geox-url:
  geoip: 'https://cdn.jsdelivr.net/gh/Loyalsoldier/v2ray-rules-dat@release/geoip.dat'
  geosite: 'https://cdn.jsdelivr.net/gh/Loyalsoldier/v2ray-rules-dat@release/geosite.dat'
  mmdb: 'https://cdn.jsdelivr.net/gh/Loyalsoldier/geoip@release/Country.mmdb'
```
1. 指定的geodata什么时候更新？是每次启动都会更新吗？配置文件里也没让指定更新时间啊。
2. ~~为什么会有两个geodata存放位置，哪个才是正在使用的？~~
 ``C:\Users\Admin\.config\clash-verge\geosite.dat`` 和 ``C:\Program Files\Clash Verge\resources\geosite.dat``
3. ~~用户配置文件指定了的话，是下载到哪里了呢？~~
