### ISSUE TITLE
v1.31 是否支持udp端口跃迁

### ISSUE THREAD

**Issue by buluw** [zzzgydi/clash-verge#528]
ports 这里用了端口范围之后 客户端无法连接服务器 显示error
目前是不是只能单端口

```yaml
proxies:
  - name: "xxxi"
    type: hysteria
    server: xxx
    ports: 40000-41000
    auth_str: xxx
    alpn:
      - h3
    protocol: udp
    up: 200
    down: 1000
    sni: xxx
    skip-cert-verify: false
    recv_window_conn: xxx
    recv_window: xxx
    disable_mtu_discovery: true
    fast-open: true
```
