### ISSUE TITLE
[feature request] add UI functionality to manually update proxy provider entries

### ISSUE THREAD

**Issue by lankylonky22** [zzzgydi/clash-verge#551]
```
proxy-providers:
  kuro:
    type: http
    url: "https://sub.xeton.dev/sub?target=clash&udp=true&new_name=true&url=😀&insert=false&config=https%3A%2F%2Fraw.githubusercontent.com%2Flankylonky22%2FClash_config%2Fmain%2Fconfig.ini"
    interval: 0
    path: ./kuro_proxy_provider.yaml
    health-check:
      enable: true
      interval: 0
      # lazy: true
      url: http://www.youtube.com/generate_204
      ```
      as uall can see, i have a disdain for auto updating, so i need a UI button to update proxy_provider entries on demand
