### ISSUE TITLE
在线订阅地址无法导入

### ISSUE THREAD

**Issue by lxy-l** [zzzgydi/clash-verge#561]
## 日志：
2023-05-10 11:24:19 INFO - [clash]: INF [API] listening addr=127.0.0.1:9090
2023-05-10 11:24:19 INFO - [clash]: INF [Inbound] Mixed(http+socks) listening addr=127.0.0.1:7890
2023-05-10 11:24:29 ERROR - error sending request for url (https://*****/我的配置文件.yaml): error trying to connect: 接收到的消息异常，或格式不正确。 (os error -2146893018)

# 问题：
但是把这个yaml文件下载下来，通过local的形式可以导入，如果直接通过链接就无法导入。

```yaml
mode: rule
mixed-port: 7890
allow-lan: false
log-level: info
secret: ""
external-controller: 127.0.0.1:9090
dns:
  enable: true
  listen: 0.0.0.0:1053
  ipv6: true
  enhanced-mode: fake-ip
  fake-ip-range: 28.0.0.1/8
  fake-ip-filter:
    - "*"
    - +.lan
  default-nameserver:
    - 223.5.5.5
  nameserver:
    - tls://8.8.4.4#dns
    - tls://1.0.0.1#dns
  proxy-server-nameserver:
    - https://doh.pub/dns-query
  nameserver-policy:
    geosite:cn,private:
      - https://doh.pub/dns-query
      - https://dns.alidns.com/dns-query
tun:
  enable: false
  stack: system
  dns-hijack:
    - any:53
  auto-route: true
  auto-detect-interface: true
profile:
  store-selected: true
  store-fake-ip: true
sniffer:
  enable: false
  sniff:
    TLS:
      ports:
        - 443
        - 8443
    HTTP:
      ports:
        - 80
        - 8080-8880
      override-destination: true
geox-url:
  geoip: https://testingcf.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@release/geoip.dat
  geosite: https://testingcf.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@release/geosite.dat
  mmdb: https://testingcf.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@release/country.mmdb
geodata-mode: true
tcp-concurrent: false
find-process-mode: strict
global-client-fingerprint: chrome
proxies:
  - name: 🇺🇸 US-V1
    server: 服务器地址
    port: 52001
    reality-opts:
      public-key: 我的key
    client-fingerprint: chrome
    type: vless
    uuid: 我的uuid
    tls: true
    tfo: false
    servername: 服务器地址
    flow: xtls-rprx-vision
    skip-cert-verify: false
  - name: 🇺🇸 US-M1
    server: 服务器地址
    port: 443
    client-fingerprint: chrome
    type: vmess
    uuid: 我的uuid
    alterId: 0
    cipher: auto
    tls: true
    tfo: false
    skip-cert-verify: false
    network: grpc
    servername: ""
    grpc-opts:
      grpc-mode: none
      grpc-service-name: images
proxy-groups:
  - name: 🚀 节点选择
    type: select
    proxies:
      - ♻️ 自动选择
      - 🇺🇸 US-V1
      - 🇺🇸 US-M1
      - DIRECT
  - name: ♻️ 自动选择
    proxies:
      - 🇺🇸 US-V1
      - 🇺🇸 US-M1
    tolerance: 100
    type: url-test
    lazy: false
    interval: 60
  - name: 📲 电报信息
    type: select
    proxies:
      - 🚀 节点选择
      - 🇺🇸 US-V1
      - 🇺🇸 US-M1
      - DIRECT
  - name: 📹 YouTube
    type: select
    proxies:
      - 🚀 节点选择
      - 🇺🇸 US-V1
      - 🇺🇸 US-M1
      - DIRECT
  - name: 🤖 OpenAI
    type: select
    proxies:
      - 🚀 节点选择
      - 🇺🇸 US-V1
      - 🇺🇸 US-M1
      - DIRECT
  - name: Ⓜ️ 微软服务
    type: select
    proxies:
      - 🚀 节点选择
      - 🇺🇸 US-V1
      - 🇺🇸 US-M1
      - DIRECT
  - name: 🍎 苹果服务
    type: select
    proxies:
      - 🚀 节点选择
      - 🇺🇸 US-V1
      - 🇺🇸 US-M1
      - DIRECT
  - name: 📢 谷歌服务
    type: select
    proxies:
      - 🚀 节点选择
      - 🇺🇸 US-V1
      - 🇺🇸 US-M1
      - DIRECT
  - name: 🎯 全球直连
    type: select
    proxies:
      - DIRECT
      - 🚀 节点选择
      - 🇺🇸 US-V1
      - 🇺🇸 US-M1
  - name: 🛑 广告拦截
    type: select
    proxies:
      - REJECT
      - 🚀 节点选择
  - name: 🐟 漏网之鱼
    type: select
    proxies:
      - 🚀 节点选择
      - 🇺🇸 US-V1
      - 🇺🇸 US-M1
      - DIRECT
rules:
  - GEOSITE,youtube,📹 YouTube
  - GEOSITE,google,📢 谷歌服务
  - GEOSITE,telegram,📲 电报信息
  - GEOSITE,openai,🤖 OpenAI
  - GEOSITE,microsoft,Ⓜ️ 微软服务
  - GEOSITE,apple,🍎 苹果服务
  - GEOSITE,category-ads, 🛑 广告拦截
  - GEOSITE,category-ads-all,🛑 广告拦截
  - GEOIP,private,🎯 全球直连,no-resolve
  - GEOIP,google,📢 谷歌服务
  - GEOIP,telegram,📲 电报信息
  - GEOSITE,geolocation-cn,🎯 全球直连
  - GEOSITE,CN,🎯 全球直连
  - GEOIP,CN,🎯 全球直连
  - MATCH,🐟 漏网之鱼

```
