### ISSUE TITLE
自动选择最快节点

### ISSUE THREAD

**Issue by IzualYang** [zzzgydi/clash-verge#567]
clash verge的merge写法，也是最终的配置结果，即修改代理组的配置为：
```yaml
proxy-groups:
  - name: Proxy
    type: url-test
    url: http://www.gstatic.com/generate_204
    interval: 600
    proxies: （后面是节点列表）
```
只要代理组有这段配置，就能定期自动选择最快节点，不管clash verge还是Clash for Windows都支持的
只不过订阅的配置文件中只有
```yaml
proxy-groups:
  - name: Proxy
    type: select
    proxies:（后面是节点列表）
```
之前用Clash for Windows的时候只需要通过parser覆写yaml配置（注意这里是没动proxies列表的）
```yaml
parsers: # array
  - url: https://机场/clash.php?sid=*****&token=************
    yaml:
      commands:
        - proxy-groups.(Proxy).type=url-test
        - proxy-groups.(Proxy).url=http://www.gstatic.com/generate_204
        - proxy-groups.(Proxy).interval=600
      prepend-rules:
        - DOMAIN-SUFFIX,v2ex.com,Proxy
```
现在用Clash Verge的merge写法，我必须手动把proxies列表写一遍，不写proxies就变成空值了；并且订阅内容一改变，我这里最终的proxies不会自动变。
script应该能实现我的目的，但是我就是不理解，明明别人几行配置的事
