### ISSUE TITLE
是否支持vless reality，如何配置？

### ISSUE THREAD

**Issue by gunsluo** [zzzgydi/clash-verge#572]
Clash Verge是否已经支持vless reality,  如果支持，是否提供配置样例。 谢谢！

```
  - name: reality
    type: vless
    server: xxx.com
    port: 443
    uuid: myuuid
    network: tcp
    servername: xxx.com
    flow: xtls-rprx-vision
    udp: true
    tls: true
    reality-opts:
      public-key: mykey
    client-fingerprint: random
```
上面网上找的配置样例，但不能工作。

**Comment by gunsluo** [comment]
配置项`short-id`没有被设置。
  
 ```
- name: reality
    type: vless
    server: xxx.com
    port: 443
    uuid: myuuid
    network: tcp
    servername: xxx.com
    flow: xtls-rprx-vision
    udp: true
    tls: true
    reality-opts:
      public-key: mykey
      short-id: 5288
    client-fingerprint: random
    ```

现在能正常工作了。
