### ISSUE TITLE
DIRECT Error, 一切正常仅显示错误。

### ISSUE THREAD

**Issue by hdchieh** [zzzgydi/clash-verge#579]
```yaml
mixed-port: ***** # HTTP(S) 和 SOCKS 代理混合端口
ipv6: true
interface-name: Wi-Fi
allow-lan: true # 允许局域网连接
bind-address: "*" # 绑定 IP 地址，仅作用于 allow-lan 为 true，'*'表示所有地址

find-process-mode: strict

mode: rule

#自定义 geodata url
geox-url:
  geoip: "https://cdn.jsdelivr.net/gh/Loyalsoldier/v2ray-rules-dat@release/geoip.dat"
  geosite: "https://cdn.jsdelivr.net/gh/Loyalsoldier/v2ray-rules-dat@release/geosite.dat"
  mmdb: "https://cdn.jsdelivr.net/gh/Loyalsoldier/geoip@release/Country.mmdb"

global-client-fingerprint: edge

# 类似于 /etc/hosts, 仅支持配置单个 IP
hosts:
# '.dev': 127.0.0.1
# 'alpha.clash.dev': '::1'
# test.com: [1.1.1.1, 2.2.2.2]
# clash.lan: clash # clash 为特别字段，将加入本地所有网卡的地址
# baidu.com: google.com # 只允许配置一个别名

profile: # 存储 select 选择记录
  store-selected: true
  
  # 持久化 fake-ip
  store-fake-ip: true

# Tun 配置
tun:
  enable: true
  stack: system # gvisor / lwip
  dns-hijack:
    - any:53 # 需要劫持的 DNS
  # auto-detect-interface: true # 自动识别出口网卡
  auto-route: true # 配置路由表
  # mtu: 9000 # 最大传输单元
  # strict-route: true # 将所有连接路由到tun来防止泄漏，但你的设备将无法其他设备被访问

# 嗅探域名 可选配置
sniffer:
  enable: true
  ## 对 redir-host 类型识别的流量进行强制嗅探
  ## 如：Tun、Redir 和 TProxy 并 DNS 为 redir-host 皆属于
  # force-dns-mapping: false
  ## 对所有未获取到域名的流量进行强制嗅探
  # parse-pure-ip: false
  # 是否使用嗅探结果作为实际访问，默认 true
  # 全局配置，优先级低于 sniffer.sniff 实际配置
  override-destination: true
  # sniff: # TLS 默认如果不配置 ports 默认嗅探 443
  #   TLS:
  #     # ports: [443, 8443]
    
  #   # 默认嗅探 80
  #   HTTP: # 需要嗅探的端口
      
  #     ports: [80, 8080-8880]
  #     # 可覆盖 sniffer.override-destination
  #     # override-destination: true
  force-domain:
    - +.v2ex.com
  ## 对嗅探结果进行跳过
  # skip-domain:
  #   - Mijia Cloud
  # 需要嗅探协议
  # 已废弃，若 sniffer.sniff 配置则此项无效
  sniffing:
    - tls
    - http
  # 强制对此域名进行嗅探
  
  # 仅对白名单中的端口进行嗅探，默认为 443，80
  # 已废弃，若 sniffer.sniff 配置则此项无效
  # port-whitelist:
  #   - "80"
  #   - "443"
    # - 8000-9999


# DNS配置
dns:
  enable: true # 关闭将使用系统 DNS
  prefer-h3: true # 开启 DoH 支持 HTTP/3，将并发尝试
  listen: 0.0.0.0:53 # 开启 DNS 服务器监听
  ipv6: true # false 将返回 AAAA 的空结果
  # ipv6-timeout: 300 # 单位：ms，内部双栈并发时，向上游查询 AAAA 时，等待 AAAA 的时间，默认 100ms
  # 用于解析 nameserver，fallback 以及其他DNS服务器配置的，DNS 服务域名
  # 只能使用纯 IP 地址，可使用加密 DNS
  default-nameserver:
    - tls://1.12.12.12:853
    - tls://223.5.5.5:853
    - tls://120.53.53.53
  enhanced-mode: fake-ip # or redir-host
  
  fake-ip-range: 198.18.0.1/16 # fake-ip 池设置
  
  # use-hosts: true # 查询 hosts
  
  # 配置不使用fake-ip的域名
  fake-ip-filter:
    - '*.lan'
    - localhost.ptlogin2.qq.com
    - +.stun.*.*
    - +.stun.*.*.*
    - +.stun.*.*.*.*
    - +.stun.*.*.*.*.*
    - "*.n.n.srv.nintendo.net"
    - +.stun.playstation.net
    - "xbox.*.*.microsoft.com"
    - "*.*.xboxlive.com"
    - "*.msftncsi.com"
    - "*.msftconnecttest.com"
    - WORKGROUP
    - "*.wecheat.cn"
  
  # DNS主要域名配置
  # 支持 UDP，TCP，DoT，DoH，DoQ
  # 这部分为主要 DNS 配置，影响所有直连，确保使用对大陆解析精准的 DNS
  nameserver:
    - 'https://223.5.5.5/dns-query#h3=true'
    - 'https://doh.pub/dns-query#h3=true' # DNS over HTTPS
    - 'https://doh.opendns.com/dns-query#h3=true' # 强制 HTTP/3，与 perfer-h3 无关，强制开启 DoH 的 HTTP/3 支持，若不支持将无法使用
    # - https://mozilla.cloudflare-dns.com/dns-query#DNS&h3=true # 指定策略组和使用 HTTP/3
    # - dhcp://en0 # dns from dhcp
    # - quic://dns.adguard.com:784 # DNS over QUIC
    # - '8.8.8.8#en0' # 兼容指定DNS出口网卡
  
  # 当配置 fallback 时，会查询 nameserver 中返回的 IP 是否为 CN，非必要配置
  # 当不是 CN，则使用 fallback 中的 DNS 查询结果
  # 确保配置 fallback 时能够正常查询
  fallback:
    - 'https://8.8.8.8/dns-query#DNS&h3=true'
    - 'https://1.1.1.1/dns-query#DNS&h3=true' # 指定 DNS 过代理查询，ProxyGroupName 为策略组名或节点名，过代理配置优先于配置出口网卡，当找不到策略组或节点名则设置为出口网卡
    - 'https://dns.twnic.tw/dns-query#h3=true'
    - 'https://dns.adguard.com/dns-query#DNS&h3=true'
  
  # 专用于节点域名解析的 DNS 服务器，非必要配置项
  # 配置服务器若查询失败将使用 nameserver，非并发查询
  # proxy-server-nameserver:
  # - https://dns.google/dns-query
  # - tls://one.one.one.one
  
  # 配置 fallback 使用条件
  # fallback-filter:
  #   geoip: true # 配置是否使用 geoip
  #   geoip-code: CN # 当 nameserver 域名的 IP 查询 geoip 库为 CN 时，不使用 fallback 中的 DNS 查询结果
  #   # 配置强制 fallback，优先于 IP 判断，具体分类自行查看 geosite 库
  #   geosite:
  #     - gfw
  #   # 如果不匹配 ipcidr 则使用 nameservers 中的结果
  #   ipcidr:
  #     - 240.0.0.0/4
  #   domain:
  #     - '+.google.com'
  #     - '+.facebook.com'
  #     - '+.youtube.com'
  
  # 配置查询域名使用的 DNS 服务器
  nameserver-policy:
    #   'www.baidu.com': '114.114.114.114'
    #   '+.internal.crop.com': '10.0.0.1'
    "*.msftncsi.com,*.msftconnecttest.com": [223.5.5.5, 114.114.114.114]
    "geosite:cn,microsoft@cn,private":
      - tls://1.12.12.12:853
      - 'https://223.5.5.5/dns-query#h3=true'
      - 'https://doh.pub/dns-query#h3=true' # DNS over HTTPS
      - 'https://doh.opendns.com/dns-query#h3=true'
    "geosite:geolocation-!cn,gfw":
      - 'https://8.8.8.8/dns-query#DNS&h3=true'
      - 'https://1.1.1.1/dns-query#DNS&h3=true'
      - 'https://dns.twnic.tw/dns-query#h3=true'
      - 'https://dns.adguard.com/dns-query#DNS&h3=true'
    # "www.baidu.com": [223.5.5.5, https://dns.alidns.com/dns-query]
    ## global，dns 为 rule-providers 中的名为 global 和 dns 规则订阅，
    ## 且 behavior 必须为 domain/classical，当为 classical 时仅会生效域名类规则 
    # "rule-set:global,dns": 8.8.8.8
proxies:

proxy-groups:
  - name: 🎯 全球直连
    type: select
    proxies:
      - DIRECT
      - REJECT
      - ♻️ 自动选择
      - 🚀 手动切换
```
