### ISSUE TITLE
配置解析bug,无法解析yaml嵌套的锚点

### ISSUE THREAD

**Issue by cmv4f** [zzzgydi/clash-verge#610]
原配置
```
PROVIDER: &PROVIDER { type: http, interval: 86400, health-check: { enable: true, url: 'http://www.gstatic.com/generate_204', interval: 300 } }
proxy-providers:
  CP: &CP { <<: *PROVIDER, path: ./providers/CP.yaml, url: 'xxx' }
  HK: { <<: *CP, filter: "HK|香港|港|\U0001F1ED\U0001F1F0|Hongkong" }
  JP: { <<: *CP, filter: 'JP|🇯🇵' }

proxy-groups:
  - { name: '🇭🇰 HK', type: select, use: [HK] }
  - { name: '🇯🇵 JP', type: select, use: [JP] }
```

Runtime Config
```
proxy-providers:
  CP:
    url: xxx
    path: ./providers/CP.yaml
    type: http
    interval: 86400
    health-check:
      enable: true
      url: http://www.gstatic.com/generate_204
      interval: 300
  HK:
    filter: HK|香港|港|🇭🇰|Hongkong
    <<:
      type: http
      interval: 86400
      health-check:
        enable: true
        url: http://www.gstatic.com/generate_204
        interval: 300
    path: ./providers/CP.yaml
    url: xxx
  JP:
    filter: JP|🇯🇵
    <<:
      type: http
      interval: 86400
      health-check:
        enable: true
        url: http://www.gstatic.com/generate_204
        interval: 300
    path: ./providers/CP.yaml
    url: xxx
```
HK，JP组中无节点
