### ISSUE TITLE
merge添加DNS不生效

### ISSUE THREAD

**Issue by aliofwind** [zzzgydi/clash-verge#65]
菜单里勾选了dns，刷新之后runtime.yaml里添加了merge进去的内容，但enable变成false
merge的内容：
```
dns:
  enable: true
  listen: :53
  enhanced-mode: redir-host
  ipv6: true
  nameserver:
    - 223.5.5.5
    - 119.29.29.29
  fallback:
    - https://1.1.1.1/dns-query
    - https://dns.google/dns-query
  fallback-filter:
    geoip: true
    geoip-code: CN
    ipcidr:
      - 240.0.0.0/4
```

**Comment by zzzgydi** [comment]
你是不是开启了tun mode，现在开启了tun mode的话，那个会同时控制tun: enable和dns: enable。。。

**Comment by aliofwind** [comment]
没有开启tun mode

**Comment by aliofwind** [comment]
```
dns:
  enable: false
  enhanced-mode: redir-host
  fallback:
    - "https://1.1.1.1/dns-query"
    - "https://dns.google/dns-query"
  fallback-filter:
    geoip: true
    geoip-code: CN
    ipcidr:
      - 240.0.0.0/4
  ipv6: true
  listen: ":53"
  nameserver:
    - 223.5.5.5
    - 119.29.29.29
tun:
  enable: false
```
现在是这样的
