### ISSUE TITLE
snell代理服务器配置解析失败

### ISSUE THREAD

**Issue by jianyun8023** [zzzgydi/clash-verge#667]
当使用代理节点类型是snell类型时，会导致节点解析失败。在设置中查看运行配置，会发现代理节点、策略组都是空的

**Comment by zzzgydi** [comment]
clash不支持snell吧

**Comment by jianyun8023** [comment]
是支持的，可以参考 [config-a-snell-proxy](https://lancellc.gitbook.io/clash/clash-config-file/proxies/config-a-snell-proxy)

**Comment by zzzgydi** [comment]
哦哦，是支持。

> 会导致节点解析失败

那这个错的话，估计是配置字段有问题吧，应该有提示错误原因吧，可以看看

**Comment by jianyun8023** [comment]
> 哦哦，是支持。
> 
> > 会导致节点解析失败
> 
> 那这个错的话，估计是配置字段有问题吧，应该有提示错误原因吧，可以看看

@zzzgydi 我使用的是linux版本，在gui界面上，配置完后，没有提示配置错误。但是可以看到运行配置中没有了代理和rule相关内容。

**Comment by zzzgydi** [comment]
方便把配置分享一下么，节点里服务器地址密码啥的敏感信息都可以去掉，剩下的原样把文件贴上来就好。

**Comment by jianyun8023** [comment]
> 方便把配置分享一下么，节点里服务器地址密码啥的敏感信息都可以去掉，剩下的原样把文件贴上来就好。

@zzzgydi 我测试过，只要加这个配置就会解析失败，version可加可不加。这个配置是我之前直接使用过的，是能用的。

```yaml
proxies:
  - name: Home
    type: snell
    server: x.snellserver.com
    port: 7788
    psk: 32618392-1DCB-4A4B-8C6F-A50F8D3B33B1
    #version: 1
```
