### ISSUE TITLE
[BUG] 必须使用127.0.0.1:7890才能上一些软件。

### ISSUE THREAD

**Issue by xLikeWATCHDOG** [zzzgydi/clash-verge#748]
**Describe the bug**
我使用Clash Verge，经过一些设置，开启了**TUN**模式，然后我想不在其他软件上再次挂代理`127.0.0.1:7890`.
于是经过了一系列尝试，发现不管怎么样，只要不挂`127.0.0.1:7890`就无法连接上。

配置文件如下：
```
mode: rule
mixed-port: 7890
allow-lan: true
log-level: info
ipv6: false
secret: ''
external-controller: 127.0.0.1:9090
dns:
  enable: true
  ipv6: false
  default-nameserver:
  - 223.5.5.5
  - 119.29.29.29
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  use-hosts: true
  nameserver:
  - https://doh.pub/dns-query
  - https://dns.alidns.com/dns-query
  fallback:
  - https://doh.dns.sb/dns-query
  - https://dns.cloudflare.com/dns-query
  - https://dns.twnic.tw/dns-query
  - tls://8.8.4.4:853
  fallback-filter:
    geoip: true
    ipcidr:
    - 240.0.0.0/4
    - 0.0.0.0/32
tun:
  enable: true
  stack: gvisor
  dns-hijack:
  - any:53
  auto-route: true
  auto-detect-interface: true
```

**To Reproduce**
1. 开启Clash verge
2. 不设置额外的代理进入telegram软件
3. 无法连接
4. 设置127.0.0.1:7890代理进入telegram软件
5. 可以连接

**Expected behavior**

**Screenshots**
<img width="928" alt="image" src="https://github.com/zzzgydi/clash-verge/assets/73741466/90406385-24c9-4cf2-bcd2-795f61fb6ded">
<img width="912" alt="image" src="https://github.com/zzzgydi/clash-verge/assets/73741466/67dd0e1c-b32f-43b1-b766-11989840e292">
<img width="928" alt="image" src="https://github.com/zzzgydi/clash-verge/assets/73741466/9114338f-128e-4292-88ce-063f61770c64">

**Information**
 - OS: macOS
 - Clash Verge Version: 1.3.6
 - Clash Core: Clash Meta

我不想额外配置代理在其他软件上！！！！！
