### ISSUE TITLE
[BUG] Profile界面Edit File的yaml高亮错误

### ISSUE THREAD

**Issue by futuretech6** [zzzgydi/clash-verge#822]
**Describe the bug**

用`[]`合并多个锚点的引用的时候，Profile的yaml高亮不对

**To Reproduce**

```yaml
speed-test: &speed-test
  url: "https://www.gstatic.com/generate_204"
  interval: 300

use-provider: &use-provider { use: [provider] }

nodes-test: &nodes-test
  type: url-test
  <<: [*use-provider, *speed-test]
  tolerance: 50
  lazy: true
  disable-udp: false

nodes-balance: &nodes-balance
  type: load-balance
  strategy: consistent-hashing
  <<: [*use-provider, *speed-test]
  lazy: true
  disable-udp: false
```

**Expected behavior**

GitHub的这个高亮就是正常的

**Screenshots**

verge的高亮截图：

![image](https://github.com/zzzgydi/clash-verge/assets/48900010/7b98f4d3-ee82-4284-8273-2dea5f37dd30)

**Information**
 - OS: Windows 10 Pro 22H2 (19045.3448)
 - Clash Verge Version: v1.3.7
 - Clash Core: v1.60.0 Meta
