### ISSUE TITLE
[Feature] 更新Clash Meta内核以便支持Hysteria2

### ISSUE THREAD

**Issue by peanut996** [zzzgydi/clash-verge#828]
**Is your feature request related to a problem? Please describe.**
请更新meta内核版本，以使用clash meta的最新特性

**Describe the solution you'd like**
主分支已经更新meta内核到`v1.16`版本，请问什么时候发布新的release版本

**Comment by peanut996** [comment]
我是手动替换的 但是期待maintainer可以直接发布新版

**Comment by Sz-Yuan** [comment]
> 我是手动替换的 但是期待maintainer可以直接发布新版

确实，发布新版更方便

**Comment by peanut996** [comment]
> > 我是手动替换的 但是期待maintainer可以直接发布新版
> 
> 确实，发布新版更方便

毕竟普通用户可能就不会操作

**Comment by jymr92** [comment]
> 自己把meta内核放到软件内核目录，也可以用的呀.

切换的时候报错，不支持hy2协议。无法切换。

**Comment by peanut996** [comment]
> > 自己把meta内核放到软件内核目录，也可以用的呀.
> 
> 切换的时候报错，不支持hy2协议。无法切换。

你换完重启软件试试

**Comment by Miroxyz** [comment]
> > 自己把meta内核放到软件内核目录，也可以用的呀.
> 
> 切换的时候报错，不支持hy2协议。无法切换。

你有没有下载错内核版本？

**Comment by chenzhiguo** [comment]
我用1.3.7版本订阅hy2的机场地址，发现节点下载不了，proxies一直是空的，是否该版本存在hy2节点解析问题？

**Comment by matianhe3** [comment]
> 我用1.3.7版本订阅hy2的机场地址，发现节点下载不了，proxies一直是空的，是否该版本存在hy2节点解析问题？

1.3.7还不支持.

**Comment by zzzgydi** [comment]
1.3.8已经更新

**Comment by chenzhiguo** [comment]
> 1.3.8已经更新

哦？我试了下机场的订阅连接，proxies还是空的哦。
```yaml
port: 7890
socks-port: 7891
redir-port: 7892
mixed-port: 7893
allow-lan: true
bind-address: '*'
mode: rule
log-level: info
ipv6: false
external-controller: '127.0.0.1:9090'
dns:
    enable: true
    ipv6: false
    listen: '0.0.0.0:53'
    enhanced-mode: fake-ip
    fake-ip-range: 198.18.0.1/16
    fake-ip-filter: ['*.lan', localhost.ptlogin2.qq.com, +.srv.nintendo.net, +.stun.playstation.net, +.msftconnecttest.com, +.msftncsi.com, +.xboxlive.com, msftconnecttest.com, 'xbox.*.microsoft.com', '*.battlenet.com.cn', '*.battlenet.com', '*.blzstatic.cn', '*.battle.net']
    nameserver: ['https://dns.alidns.com/dns-query', '223.5.5.5#DIRECT', '119.29.29.29#DIRECT']
    fallback: ['https://cloudflare-dns.com/dns-query#♻️ 自动选择', 'https://dns.google/dns-query#♻️ 自动选择', 'https://dns.alidns.com/dns-query', 'tls://8.8.4.4:853#♻️ 自动选择']
    fallback-filter: { geoip: true, geoip-code: CN, ipcidr: [240.0.0.0/4, 0.0.0.0/32] }
proxies: []
proxy-groups:
    - { name: '🌏 全球加速', type: select, proxies: ['♻️ 自动选择', '🚀 手动切换', DIRECT] }
    - { name: '🍎 苹果服务', type: select, proxies: ['🌏 全球加速'] }
    - { name: '🤖 OpenAi', type: select, proxies: ['🌏 全球加速'] }
    - { name: '📺 YouTube', type: select, proxies: ['🌏 全球加速'] }
    - { name: '🎬 国际媒体', type: select, proxies: ['🌏 全球加速'] }
    - { name: '🌌 谷歌服务', type: select, proxies: ['🌏 全球加速'] }
    - { name: '📟 电报消息', type: select, proxies: ['🌏 全球加速'] }
    - { name: '🐦 推特服务', type: select, proxies: ['🌏 全球加速'] }
    - { name: '🎮 游戏平台', type: select, proxies: ['🌏 全球加速'] }
    - { name: '🆎 AdBlock', type: select, proxies: [REJECT] }
rule-providers:
    Direct: { type: http, behavior: domain, interval: 86400, url: 'https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/Direct/Direct.yaml', path: ./ruleset/Direct.yaml }
    Lan: { type: http, behavior: classical, interval: 86400, url: 'https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/Lan/Lan.yaml', path: ./ruleset/Lan.yaml }
    Download: { type: http, behavior: classical, interval: 86400, url: 'https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/Download/Download.yaml', path: ./ruleset/Download.yaml }
    Ad: { type: http, behavior: domain, interval: 86400, url: 'https://anti-ad.net/clash.yaml', path: ./ruleset/anti-ad-clash.yaml }
    OpenAi: { type: http, behavior: classical, interval: 86400, url: 'https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/OpenAI/OpenAI.yaml', path: ./ruleset/OpenAi.yaml }
    BiliBili: { type: http, behavior: classical, interval: 86400, url: 'https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/BiliBili/BiliBili.yaml', path: ./ruleset/BiliBili.yaml }
    YouTube: { type: http, behavior: classical, interval: 86400, url: 'https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/YouTube/YouTube.yaml', path: ./ruleset/YouTube.yaml }
    Netflix: { type: http, behavior: classical, interval: 86400, url: 'https://cdn.jsdelivr.net/gh/tututo/Profiles@master/Clash/RuleSet/StreamingMedia/Streaming.yaml', path: ./ruleset/Streaming.yaml }
    GlobalMedia: { type: http, behavior: classical, interval: 86400, url: 'https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/GlobalMedia/GlobalMedia_Classical.yaml', path: ./ruleset/GlobalMedia.yaml }
    Apple: { type: http, behavior: classical, interval: 86400, url: 'https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/Apple/Apple_Classical.yaml', path: ./ruleset/Apple.yaml }
    Github: { type: http, behavior: classical, interval: 86400, url: 'https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/GitHub/GitHub.yaml', path: ./ruleset/Github.yaml }
    Microsoft: { type: http, behavior: classical, interval: 86400, url: 'https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/Microsoft/Microsoft.yaml', path: ./ruleset/Microsoft.yaml }
    Google: { type: http, behavior: classical, interval: 86400, url: 'https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/Google/Google.yaml', path: ./ruleset/Google.yaml }
    Telegram: { type: http, behavior: classical, interval: 86400, url: 'https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/Telegram/Telegram.yaml', path: ./ruleset/Telegram.yaml }
    Twitter: { type: http, behavior: classical, interval: 86400, url: 'https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/Twitter/Twitter.yaml', path: ./ruleset/Twitter.yaml }
    Game: { type: http, behavior: classical, interval: 86400, url: 'https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/Game/Game.yaml', path: ./ruleset/Game.yaml }
    ChinaIP: { type: http, behavior: ipcidr, interval: 86400, url: 'https://cdn.jsdelivr.net/gh/soffchen/GeoIP2-CN@release/clash-rule-provider.yml', path: ./ruleset/ChinaIP.yaml }
    ProxyLite: { type: http, behavior: classical, interval: 86400, url: 'https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/ProxyLite/ProxyLite.yaml', path: ./ruleset/ProxyLite.yaml }
rules:
    - 'DOMAIN,api.xjichang.buzz,DIRECT'
    - 'RULE-SET,Direct,DIRECT'
    - 'RULE-SET,Lan,DIRECT'
```
