### ISSUE TITLE
[BUG]DNS等YAML Merge工作不及预期效果

### ISSUE THREAD

**Issue by HAMAN23333** [zzzgydi/clash-verge#831]
## 这是 DNS 配置的预期效果
```yaml
dns:
  enable: true
  listen: :1053
  ipv6: true
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter: []
  default-nameserver:
    - 119.29.29.29
    - 223.5.5.5
  nameserver:
    - "tls://8.8.4.4#DNS"
    - "tls://1.0.0.1#DNS"
  proxy-server-nameserver:
    - https://doh.pub/dns-query
    - https://dns.alidns.com/dns-query
  nameserver-policy:
    "rule-set:ChinaMax,ChinaMax_Domain":
      - https://doh.pub/dns-query
      - https://dns.alidns.com/dns-query
```
## 这是 DNS 配置的实际效果
```yaml
dns:
  enable: true
  listen: :1053
  ipv6: true
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter: []
  default-nameserver:
  - 119.29.29.29
  - 223.5.5.5
  nameserver:
  - tls://8.8.4.4#DNS
  - tls://1.0.0.1#DNS
  proxy-server-nameserver:
  - https://doh.pub/dns-query
  - https://dns.alidns.com/dns-query
  nameserver-policy:
    rule-set:ChinaMax,ChinaMax_Domain:
    - https://doh.pub/dns-query
    - https://dns.alidns.com/dns-query
```
可以看到 nameserver 的双引号"被忽略了，导致配置不生效，无法正常选择DNS服务器
