### ISSUE TITLE
[BUG]开启TUN的情况下，WSA偶发性无法连接

### ISSUE THREAD

**Issue by HAMAN23333** [zzzgydi/clash-verge#846]
**Describe the bug**
WSA有时能连接网络，有时直接无网络，第一张图为无法连接网络的情况，第二三张为正常连接的情况
在无法连接的情况下，Verge的日志也没有任何记录，尝试过修改子系统的DNS也无效，在Clash for windows下没有此问题
Verge配置如下：
```yaml
tun:
  enable: true
  stack: mixed
  dns-hijack:
    - 'any:53'
    - 'tcp://any:53'
  auto-route: true
  auto-detect-interface: true

dns:
  enable: true
  listen: :53
  ipv6: true
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter: []
  default-nameserver:
    - 119.29.29.29
    - 223.5.5.5
  nameserver:
    - 'https://1.1.1.1/dns-query#DNS'
    - 'https://dns.google/dns-query#DNS'
  proxy-server-nameserver:
    - https://doh.pub/dns-query
    - https://dns.alidns.com/dns-query
  nameserver-policy:
    "rule-set:ChinaMax,ChinaMax_Domain":
      - https://doh.pub/dns-query
      - https://dns.alidns.com/dns-query
    "rule-set:Lan":
      - 192.168.50.1
```

**Screenshots**
![image](https://github.com/zzzgydi/clash-verge/assets/80085265/54e84155-80ab-473e-aacd-55177026f688)
![image](https://github.com/zzzgydi/clash-verge/assets/80085265/d001e324-a265-46c2-a54f-5b7a6f070761)
![image](https://github.com/zzzgydi/clash-verge/assets/80085265/fffe43b4-0202-4e5b-9b82-f33c270ba18a)

**Information**
 - OS: Windows 11 22621.2428
 - Clash Verge Version: 1.3.7
 - Clash Core:  Clash Meta
