### ISSUE TITLE
[BUG] fake-ip-filter列表中的地址无法直连

### ISSUE THREAD

**Issue by NueXini** [zzzgydi/clash-verge#878]
`Merge`配置：
```yaml
# Merge Template for clash verge
# The `Merge` format used to enhance profile

prepend-rules:

prepend-proxies:

prepend-proxy-groups:

append-rules:
  dns: 
    enable: true
    ipv6: false
    enhanced-mode: fake-ip
    fake-ip-filter: 
      - '*.lan'
      - '*.qq.com'
      - localhost.ptlogin2.qq.com
      - localhost.sec.qq.com
      - +.stun.*.*
      - +.stun.*.*.*
      - +.stun.*.*.*.*
      - +.stun.*.*.*.*.*
      - WORKGROUP
    default-nameserver:
      - 223.5.5.5
      - https://223.5.5.5/dns-query
    nameserver: 
      - 223.5.5.5
      - https://223.5.5.5/dns-query
    fallback: 
      - https://1.1.1.1/dns-query
      - 8.8.4.4

append-proxies:

append-proxy-groups:

```

![image](https://github.com/zzzgydi/clash-verge/assets/34617094/6542c210-9cdd-459f-92af-3fcb7089cf09)

![image](https://github.com/zzzgydi/clash-verge/assets/34617094/d3a0ba73-aa3e-41ab-8706-49aaadc116f9)
