### ISSUE TITLE
[Feature]希望增加配置文件预处理功能

### ISSUE THREAD

**Issue by HalfNew** [zzzgydi/clash-verge#893]
像cfw一样，除了机场的配置规则之外，可以支持用户自定义的规则（更新订阅不会导致自定义的规则消失）

**Comment by bestsanmao** [comment]
同求Parsers功能

**Comment by visense** [comment]
同求，自己添加排除某个程序不走代理，比如finalshell等

**Comment by bestsanmao** [comment]
> 在说这些之前有看过wiki么 [Merge 合并处理](https://github.com/zzzgydi/clash-verge/wiki/%E4%BD%BF%E7%94%A8%E6%8C%87%E5%8D%97#merge-%E5%90%88%E5%B9%B6%E5%A4%84%E7%90%86) 我觉得可以close了

在试这个功能
好像不生效
请问有示例吗

**Comment by visense** [comment]
merge我测试append rules 没有生效，大家成功过吗？

**Comment by zzzgydi** [comment]
注意一下，merge不是什么字段都支持的，并不完全支持cfw的commands，详细的看wiki

**Comment by zzzgydi** [comment]
@visense 你这个格式有问题

**Comment by RyanLeigh1221** [comment]
> 注意一下，merge不是什么字段都支持的，并不完全支持cfw的commands，详细的看wiki

希望支持cfw的  commands
        - proxy-groups.0.proxies.0+DIRECT
        - proxy-groups.0.proxies.0+REJECT
 還蠻好用的

**Comment by abrclano** [comment]
> > 在说这些之前有看过wiki么 [Merge 合并处理](https://github.com/zzzgydi/clash-verge/wiki/%E4%BD%BF%E7%94%A8%E6%8C%87%E5%8D%97#merge-%E5%90%88%E5%B9%B6%E5%A4%84%E7%90%86) 我觉得可以close了
> 
> 在试这个功能 好像不生效 请问有示例吗

我个人觉得yaml的语法格式不是很灵活，用JavaScript要方便一些，这是我的配置https://github.com/abrclano/Self-use-Rules/tree/main/Clash.verge 你可以看看

**Comment by visense** [comment]
> @visense 你这个格式有问题

感谢大佬，成功了！

**Comment by test482** [comment]
merge.yaml:

```yaml
proxy-groups:
  - name: 自动选择
    type: url-test
    url: http://www.gstatic.com/generate_204
    interval: 600
    tolerance: 50
    lazy: true
    proxies:
      - 上海联通转台湾HiNet[M][Trojan][倍率:1]

  - name: 手动选择
    type: select
    proxies:
      - 上海联通转台湾HiNet[M][Trojan][倍率:1]

  - name: 香港节点
    type: url-test
    url: http://www.gstatic.com/generate_204
    interval: 600
    tolerance: 50
    lazy: true
    proxies:
      - 上海联通转台湾HiNet[M][Trojan][倍率:1]
```

请问像上述配置的话，该如何在 proxies 处引用“订阅链接中的全部节点”、“订阅链接中 name 包含 `HK|香港|港|Hong Kong` 字样的节点”呢？
